version: '3'
services: 
  enodeb:
    image: openverso/srs-lte:20_04_1
    command: 
      - enb
    privileged: true
    cap_add:
      - all
    environment:
      MME_HOSTNAME: mme
      ENB_HOSTNAME: enodeb
      UE_HOSTNAME: ue

  ue:
    image: openverso/srs-lte:20_04_1
    command: 
      - ue
    privileged: true
    cap_add:
      - all
    environment:
      ENB_HOSTNAME: enodeb
      UE_HOSTNAME: ue
      MCC: "001"
      MNC: "01"
      MSISDN: "0123456789"
      OPC: "63bfa50ee6523365ff14c1f45f88737d"
      KEY: "00112233445566778899aabbccddeeff"

