version: '3'
services: 
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: open5gs
  amf:
    image: openverso/open5gs:2.2.3
    command: 
      - open5gs-amfd 
    restart : on-failure
    ports:
      - 36412:36412
    volumes:
      - ./open5gs-config/amf.yaml:/opt/open5gs/etc/open5gs/amf.yaml
  ausf:
    image: openverso/open5gs:2.2.3
    command: 
      - open5gs-ausfd
    restart : on-failure
  nrf:
    image: openverso/open5gs:2.2.3
    command: open5gs-nrfd   
    restart : on-failure 
    ports:
      - 7777:7777
  nssf:
    image: openverso/open5gs:2.2.3
    command: open5gs-nssfd   
    restart : on-failure 
  pcf:
    image: openverso/open5gs:2.2.3
    command: 
      - open5gs-pcfd
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart : on-failure
  pcrf:
    image: openverso/open5gs:2.2.3
    command: ["open5gs-pcrfd"]
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
  smf:
    image: openverso/open5gs:2.2.3
    command: open5gs-smfd    
    restart : on-failure 
  udm:
    image: openverso/open5gs:2.2.3
    restart: on-failure
    command: 
      - open5gs-udmd
  udr:
    image: openverso/open5gs:2.2.3
    restart: on-failure
    environment:
      DB_URI: mongodb://mongo/open5gs
    command: 
      - open5gs-udrd
  upf:
    image: openverso/open5gs:2.2.3
    command:
      - open5gs-upfd
    cap_add:
      - all
    privileged: true
    restart: on-failure
    ports:
      - 2152:2152
  webui:
    image: openverso/open5gs-webui:2.2.3  
    restart: on-failure
    environment:
      DB_URI: mongodb://mongo/open5gs
    ports:
      - 3000:3000
  portainer:
    image: portainer/portainer-ce
    ports:
    - 9000:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
