version: '3'
services: 
  gnodeb:
    image: openverso/oai-gnb:2021.w28-uhd-images
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    cap_add:
      - all
    environment:
        MODE: SA
        AMF_HOSTNAME: amf
        MCC: 901
        MNC: 70
        TAC: 1
